### ISSUE TITLE
[Enhancement] Improve Package Imports for Code Readability

### ISSUE THREAD

**Issue by RathodBhakti** [yagnik2411/Quiz-Genius#100]
**Current Scenario:**
The code currently uses long package imports that are not managed properly, which makes it difficult to read and understand.

**Proposed Improvement:**
Use Short Imports: Refactor the code to use short imports to enhance clarity.
Import Order: Organize imports as follows:
- Dart imports first
- Flutter and third-party package imports second
- Local folder imports last

**Benefits:**
Improved Code Readability: Shorter and organized imports will make the code easier to read and maintain.
Clear Separation of Imports: Helps in understanding the dependencies and structure of the project better.

**Request:**
I would like to perform this enhancement. Please assign this issue to me and add the hacktoberfest-accepted label.

**Comment by KirolosMFahem** [comment]
I'd like you to make a small change 
I'd like you to make 

1. Dart imports 
2. Flutter imports 
3. Local folder imports
4. third-party package imports

**Comment by RathodBhakti** [comment]
Hi @KirolosMFahem ,

Thank you for giving me the chance to contribute to your repository! Since your repository is participating in Hacktoberfest, could you please add the **hacktoberfest-accepted** label also? It would really help me in my Hacktoberfest journey.

Thanks again!

**Comment by KirolosMFahem** [comment]
since it's not a level 2 I can't add hacktoberfest-accepted
