### ISSUE TITLE
[BUG] the Hard-TF Quiz is showing a RangeError

### ISSUE THREAD

**Issue by Yash05080** [yagnik2411/Quiz-Genius#101]
**Description :**

the hard mode in true false quiz is showing  :

RangeError (length): Invalid value: Not in inclusive range

we are seeing this error because all the question are unable to load while fetching the data which resulted in the following error.

**Steps to reproduce the behaviour :**
1. Go to "New Quiz"
2. Click on 'Hard' in difficulty type
3. Click on 'True/False Quiz' in quiz type
4. Scroll down to last question
5. See error

**Expected behaviour:**
when the questions are unable to load, there should be a retry option so that user can manually refresh the question to overcome this issue as this issue depends not only on the backend but also on the user internet speed.
we should also increase the fetching time to ensure that all the questions have been loaded first.

**Screenshots**
<img width="220" alt="Screenshot 2024-10-16 at 1 25 15 PM" src="https://github.com/user-attachments/assets/9d4fb083-462a-4dcf-8459-08436329045a">
<img width="220" alt="Screenshot 2024-10-16 at 1 35 05 PM" src="https://github.com/user-attachments/assets/ad80a424-72c7-4cd8-9dd3-bdb5d4df6760">

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by yagnik2411** [comment]
@KirolosMFahem hactoberfest label for issue and hacktoberfest-accepted for PR

**Comment by Yash05080** [comment]
i worked on it and discovered that the error we are encountering is because the api is unable to provide the required no. of those specific questions (hard- tf type) , the error in the screenshots tells that in first attempt there were only 7 questions of this type and in second attempt there were only 8 questions of this type.
to solve this, the efficient way which i can think of is that we call the api after the question type and difficulty type has been chosen.
therefore we will only ask the api to return those specific type of questions.

not only will doing that solve the current issue, but also if we add a instruction page before the quiz start, we can enhance user experience by starting the timer after user clicks on start quiz on that new instruction page.

we will make it so that the user can not start the quiz until the questions have been loaded which would avoid the use of circular progressing indicator.


alternative for that is :

we can call the api again if insufficient amount of questions have been added to the quiz list and add the remaining questions after that. This method will also work fine but in future expansion if we are to add more types of quiz or lets say more customised version of quizes with more no. of question, it will not be as efficient.

which method should i go for?

**Comment by KirolosMFahem** [comment]
> @KirolosMFahem hactoberfest label for issue and hacktoberfest-accepted for PR

@yagnik2411 keep notes like this in privet on Discord

**Comment by KirolosMFahem** [comment]
> @KirolosMFahem hactoberfest label for issue and hacktoberfest-accepted for PR

keep notes like this in privet

**Comment by KirolosMFahem** [comment]
> i worked on it and discovered that the error we are encountering is because the api is unable to provide the required no. of those specific questions (hard- tf type) , the error in the screenshots tells that in first attempt there were only 7 questions of this type and in second attempt there were only 8 questions of this type. to solve this, the efficient way which i can think of is that we call the api after the question type and difficulty type has been chosen. therefore we will only ask the api to return those specific type of questions.
> 
> not only will doing that solve the current issue, but also if we add a instruction page before the quiz start, we can enhance user experience by starting the timer after user clicks on start quiz on that new instruction page.
> 
> we will make it so that the user can not start the quiz until the questions have been loaded which would avoid the use of circular progressing indicator.
> 
> alternative for that is :
> 
> we can call the api again if insufficient amount of questions have been added to the quiz list and add the remaining questions after that. This method will also work fine but in future expansion if we are to add more types of quiz or lets say more customised version of quizes with more no. of question, it will not be as efficient.
> 
> which method should i go for?

Thank you for your thorough analysis. I recommend going with the first solution:

Call the API after question type and difficulty are chosen: This approach is more efficient and scalable. It ensures that the quiz is ready to start with the correct number of questions without additional API calls.
Adding an instruction page: This will enhance user experience by allowing users to start the quiz only after the questions are loaded, avoiding the circular progress indicator.
Implementing this method will be more future-proof for adding more quiz types or customized versions with more questions.

**Comment by yagnik2411** [comment]
@Yash05080 one thing if API returns a question below our limited you can set size quiz list to number questions returned by API. we do not call API again.

**Comment by Yash05080** [comment]
@yagnik2411 yes i can do that but will that be alright to have uneven no. of questions because sometimes it may be 7 sometimes 8 and i think it will be better if we keep the question number same i.e. 10 . so which method should i go for?

**Comment by Yash05080** [comment]
i have solved the issue with the first method that was decided and it is working well, where i call the api to give me only the specific questions. shall i open a pull request?

**Comment by Yash05080** [comment]
what error are we encountering?

**Comment by KirolosMFahem** [comment]
nothing just waiting for @yagnik2411 to merge it
