### ISSUE TITLE
[Documentation] Update README

### ISSUE THREAD

**Issue by Annapoornaaradhya** [yagnik2411/Quiz-Genius#111]
**Current Documentation**:
The This project is now OFFICIALLY accepted for section hacktoberfest banner is too big I would like to arrange them properly in form of a table.

**Proposed Changes**:
![image](https://github.com/user-attachments/assets/0b60544d-0523-4dc0-8386-181de7188cb7)

**Reasons for Update**:
The section is not clear
![image](https://github.com/user-attachments/assets/9348bd46-6807-4df4-8e3d-d771c5095928)

**Assignee**:
@yagnik2411 Please assign this issue to me, as I would like to contribute to the documentation improvements. under gssoc-ext level and hacktoberfest accecpted

Thank you

**Comment by yagnik2411** [comment]
also add table of content in readme like #93
