### ISSUE TITLE
[BUG] Widget Overflow

### ISSUE THREAD

**Issue by Dhruv80576** [yagnik2411/Quiz-Genius#117]
**Describe the bug**  
Widget on the navigation panel overflows

**To Reproduce**  
1. Go to side panel
2. see the error
**Expected behavior**  
It should not overflow

**Screenshots**  
![image](https://github.com/user-attachments/assets/bdbc7e85-3072-4591-8726-a16f52e26704)

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by KirolosMFahem** [comment]
you're on it @Dhruv80576
