### ISSUE TITLE
[BUG] No previous quiz displayed

### ISSUE THREAD

**Issue by Dhruv80576** [yagnik2411/Quiz-Genius#118]
**Describe the bug**  
Previous Quiz screen doesn't show any previous quiz even after attempting quiz.
**To Reproduce**  
1. Give some quiz
2. Click on 'previous scores
3. See error

**Expected behavior**  
It should show past record of quiz attempted by the user.

**Screenshots**  
![image](https://github.com/user-attachments/assets/e75a523c-ff92-494b-b6e8-1fd7a0d84ac6)

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by KirolosMFahem** [comment]
you're on it @Dhruv80576
