### ISSUE TITLE
[BUG] Authentication not persistent

### ISSUE THREAD

**Issue by Dhruv80576** [yagnik2411/Quiz-Genius#120]
**Describe the bug**  
User need to login each time it opens application.

**To Reproduce**  
1. Close app
2. Reopen the app
3. You need to login each time you open app

**Expected behavior**  
App should be persistent i.e. it should remain logged in even after closing application.

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by KirolosMFahem** [comment]
there is an issue opened for it go check issue #45 
and make a proposal there
