### ISSUE TITLE
[Documentation] : Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [yagnik2411/Quiz-Genius#131]
**Current Documentation**:
The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

**Proposed Changes**:
Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

**Reasons for Update**:
Structure is not perfect and also some sections are yet to be added

**Additional Context**:
- [Add any other context about the documentation update request, such as links to relevant discussions, previous versions of the documentation, etc.

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to the documentation improvements.

**Comment by KirolosMFahem** [comment]
you're on it @milansamuel609

**Comment by milansamuel609** [comment]
> you're on it @milansamuel609

Sure 😊
