### ISSUE TITLE
[BUG 🐞] new quiz tab not working in drawer 

### ISSUE THREAD

**Issue by WednesdaySP** [yagnik2411/Quiz-Genius#141]
**Describe the bug**  
The new quiz tab is not opening on clicking, in drawer section.

**Screenshots**  

https://github.com/user-attachments/assets/4cc69d56-efff-4073-ad8b-eff0830383c5

I would like to fix this issue, please assign me.

**Comment by KirolosMFahem** [comment]
you're on it @WednesdaySP
