### ISSUE TITLE
Implement Issue open/close message workflow automation🚀

### ISSUE THREAD

**Issue by amiya-cyber** [yagnik2411/Quiz-Genius#142]
Workflow Description:

This workflow automates messages when an issue is opened or closed. When a new issue is opened, it posts a welcome message to guide the submitter. When an issue is closed, it posts a thank-you message, acknowledging the resolution.

This helps improve communication and maintain consistency in issue management.

please assign me with level3 label @yagnik2411

**Comment by KirolosMFahem** [comment]
hi @amiya-cyber as you see we already have a workflow but if you want to improve it
you're on it

**Comment by amiya-cyber** [comment]
Hello @KirolosMFahem  I have improved the workflow can you add level 2 to this pr
