### ISSUE TITLE
PULL REQUEST RAISE WORKFLOW AUTOMATION🚀

### ISSUE THREAD

**Issue by amiya-cyber** [yagnik2411/Quiz-Genius#146]
This workflow automates messages when a PULL REQUEST is opened or raised. When a new pr is opened, it posts a welcome message to guide the submitter.

This helps improve communication and maintain consistency in pull request management.

please @yagnik2411 add level 3 label and assign

**Comment by KirolosMFahem** [comment]
there's already one
