### ISSUE TITLE
[Documentation] Want to add security policy in.md file 

### ISSUE THREAD

**Issue by Dipanita45** [yagnik2411/Quiz-Genius#152]
**Current Documentation**:
.

**Proposed Changes**:
Want to add security policy to protect the website against the harms 

*

*

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to the documentation improvements.
 Please assign me the issue 
@yagnik2411

**Comment by KirolosMFahem** [comment]
please note that's what you're talking about is related to legal work

anyway you're on it
