### ISSUE TITLE
Functionality : Adding Different Question Types

### ISSUE THREAD

**Issue by Oitanny** [yagnik2411/Quiz-Genius#16]
A quiz can comprise various types of questions:

| **Question Type**         | **Description**                                              |
|---------------------------|--------------------------------------------------------------|
| **Multiple Choice (MCQ)**  | Choose one correct answer from several options.              |
| **True/False**             | Decide whether a statement is true or false.                 |
| **Fill in the Blank**      | Type the correct answer to fill in the blank.                |
| **Picture-Based**          | Answer a question based on an image shown.                   |
| **Match the Following**    | Match pairs of items from two columns.                       |
| **Ordering/Sequencing**    | Arrange items in the correct order.                          |
| **Text Input/Short Answer**| Type a brief response to answer the question.                |
| **Checkbox (Multi-Select)**| Select all correct answers from multiple options.            |
| **Numeric Input**          | Input a numerical answer.                                    |
| **Flashcards**             | Self-evaluation by flipping cards to see answers.            |

This feature is currently : not implemented

**Comment by ezsarthak** [comment]
Hello,

I would love to work on this and contribute to the project.

Thank you!

**Comment by yagnik2411** [comment]
but API is not able to give a response for this much.
@Oitanny do you have any other way?

**Comment by ezsarthak** [comment]
The API is being used for the True False Quiz. The same website also provides MCQ API, for others I'll make API and host it on GitHub. Can you please increase the level? I would love to work.

**Comment by ezsarthak** [comment]
I added a feature where the user can choose between the quiz types. Please assign this to me so I can contribute to the project.

**Comment by yagnik2411** [comment]
- [ ] are you participating in hacktober-fest?
- [ ] are you participating in gssoc?

**Comment by ezsarthak** [comment]
@yagnik2411 both

**Comment by yagnik2411** [comment]
https://chat.whatsapp.com/FaQ28sTUMDPCY64JezzUoh
join this community for discussion

**Comment by yagnik2411** [comment]
@Oitanny look at the website how much type of question you can create and use same website for different type of question

**Comment by ezsarthak** [comment]
The Website has only MCQ and True False type of Quiz API. I have created a pull request in which I have used the same API for MCQ and the User can choose between Quiz types. I would love if it gets merged.

**Comment by yagnik2411** [comment]
sorry for inconvenience, i will your PR before EOD of 7-10-24
