### ISSUE TITLE
Bug: Entity codes displayed instead of the required character

### ISSUE THREAD

**Issue by aashika-j18** [yagnik2411/Quiz-Genius#19]
I've noticed that the entity codes are being displayed instead of the actual characters in the quiz questions.
Egs: &-quot; in place of quotes(") and &-#039; in place of apostrophe(')

![WhatsApp Image 2024-10-02 at 19 47 21_3e78b323](https://github.com/user-attachments/assets/de141d1c-c1d9-40f9-88d4-7590eb455702)

**Comment by aashika-j18** [comment]
I would love to work on this under GSSoC Extd and Hacktoberfest! Please assign it to me.

**Comment by shashank-lol** [comment]
Pls assign this issue to me

**Comment by yagnik2411** [comment]
this is not a bug, this behaviour happens because of API.
https://chat.whatsapp.com/FaQ28sTUMDPCY64JezzUoh
join this community for a discussion

**Comment by aashika-j18** [comment]
Hi @yagnik2411 !
I was able to fix this issue. Now the quotes and apostrophe are being displayed correctly.
![image](https://github.com/user-attachments/assets/f9f2393a-0119-415c-81b2-d4a86333ed0b)
It would be great if i can contribute to this under gssoc-ext and hacktoberfest.

Should i create a new issue? Or can this be reopened?
Sorry for the late response

**Comment by KirolosMFahem** [comment]
@aashika-j18 this can be reopened just create a PR and we'll take a look at it
just mention the issue number

**Comment by KirolosMFahem** [comment]
this can be reopened

**Comment by aashika-j18** [comment]
> @aashika-j18 this can be reopened just create a PR and we'll take a look at it just mention the issue number

Thank You @KirolosMFahem !
Yes sure
Please assign this issue to me
