### ISSUE TITLE
I am trying to make a pull request but i failed due to 0 review from author 

### ISSUE THREAD

**Issue by Nimitshekhawat** [yagnik2411/Quiz-Genius#21]
hi, i am new to this open source but i've some basic knowledge of this . They said at leaset one review is required and i review it for then 5 times and also add comment where i change the code but it still give me error while making the pull request

**Comment by yagnik2411** [comment]
only the owner or collaborator can merge or review it so be patient

**Comment by KirolosMFahem** [comment]
As I see you've created a PR so all you've to do is let @yagnik2411 review it, and then he'll decide whether to merge it or not
