### ISSUE TITLE
missing tags (topics)

### ISSUE THREAD

**Issue by KirolosMFahem** [yagnik2411/Quiz-Genius#22]
Hi @yagnik2411 
please add the following tags (topics) to the home of the repo profile as GSSoC requires it as a part of their collaboration with hacktoberfest alongside to GSSoC tags (topics)

hacktoberfest
hacktoberfest-accepted

please after it's done close with a comment

**Comment by yagnik2411** [comment]
@KirolosMFahem check it on page , i add all tag which you told

**Comment by KirolosMFahem** [comment]
done
