### ISSUE TITLE
Incorrect Credentials Not Showing Clear Error Message

### ISSUE THREAD

**Issue by MaRyamFatima1120** [yagnik2411/Quiz-Genius#23]
Hi,

I found that when a user enters incorrect login credentials (email or password), the app does not display a clear error message. To improve the user experience, I suggest displaying a message such as:

“Invalid email or password”
This will provide better feedback and help users understand why they cannot log in.

Best Regards,
Maryam Fatima

**Comment by ezsarthak** [comment]
Hello @yagnik2411 ,
I solved this issue. Please assign this to me so I can contribute to the project.
Thank You.

**Comment by yagnik2411** [comment]
@ezsarthak  you need to make PR

**Comment by yagnik2411** [comment]
- [ ] are you participating in hacktober-fest?
- [ ] are you participating in gssoc?

**Comment by ezsarthak** [comment]
> * [yes ]  are you participating in hacktober-fest?
> * [yes ]  are you participating in gssoc?

**Comment by ezsarthak** [comment]
@yagnik2411  Participating in both

**Comment by yagnik2411** [comment]
https://chat.whatsapp.com/FaQ28sTUMDPCY64JezzUoh
join this community for discussion
