### ISSUE TITLE
Issues with Signup, Login, and User Interaction

### ISSUE THREAD

**Issue by MaRyamFatima1120** [yagnik2411/Quiz-Genius#24]
Hi ,
I found several issues related to the signup, login screens, and user interaction:

1. Email and Password Fields Styling: On the signup screen, when the user clicks on the email or password fields, the underline  & label turns purple, . This contrast may not be ideal, and it should be changed for better visibility.
2. Forgot Password Option Missing: The login screen is missing a "Forgot Password" option, which is essential for user convenience.
3. Password Not Obscured: The password field should be obscured (masked) by default for security reasons.
4. Login/Sign Up Flow Issue: After a failed login, the user is redirected to the signup screen, but if they try to sign up with an already registered email, they receive a message like "Email already signed up." However, there is no option to go back to the login screen, forcing the user to use the mobile back button, which closes the app. This can be frustrating and disrupts the user experience.
5.  Long names cause rendering issues with the RenderFlex widget, leading to improper display or overflow.
6. I've noticed that the circular progress indicator appears purple when users click. I suggest changing the color to align with the app's overall theme for better visual consistency.

<img width="206" alt="Screenshot 2024-10-03 094841" src="https://github.com/user-attachments/assets/55af637e-8576-4a4d-9e3c-00fef70b3901">,

<img width="184" alt="Screenshot 2024-10-03 095324" src="https://github.com/user-attachments/assets/25115c72-60c4-4215-b3af-bb0150e94279">

I believe fixing these issues will greatly improve the app’s usability.

Best Regards,
Maryam Fatima

**Comment by MaRyamFatima1120** [comment]
@yagnik2411 Please assign it me.

**Comment by yagnik2411** [comment]
- [ ] are you participating in hacktober-fest?
- [ ] are you participating in gssoc?

**Comment by MaRyamFatima1120** [comment]
I am participating in gssco.

**Comment by yagnik2411** [comment]
@MaRyamFatima1120 hacktoberfest-test

**Comment by MaRyamFatima1120** [comment]
@yagnik2411 Please assign this to me.

**Comment by MaRyamFatima1120** [comment]
Hi @yagnik2411 
I want to clarify that the issue @Reboot2004 mentioned about adding multiple authentication methods (Facebook, email, etc.) is different from what I’m working on. My tasks focus on UI/UX, like field styling, the "Forgot Password" option, and login flow improvements.

Since these are separate issues, could you please allow Reboot to proceed with the authentication work?

@Reboot2004, let me know if I’m right about this!

**Comment by CodewithAnn** [comment]
@KirolosMFahem @yagnik2411 please assign this to me, let me fix this issue.

**Comment by yagnik2411** [comment]
@MaRyamFatima1120 do you want to work on it? If you don't wish to then assign this to @CodewithAnn .

**Comment by MaRyamFatima1120** [comment]
@yagnik2411  Yes, I am currently working on the issue and would like to continue. Please let @CodewithAnn know that I  am already working on this and will resolve the issue.

**Comment by KirolosMFahem** [comment]
@CodewithAnn you're on it

**Comment by WednesdaySP** [comment]
@KirolosMFahem i would like to work on this issue, if this issue is not resolved please assign it to me.

**Comment by KirolosMFahem** [comment]
@WednesdaySP you're on it
