### ISSUE TITLE
Suggestion to Add Image Picker for Profile Customization

### ISSUE THREAD

**Issue by MaRyamFatima1120** [yagnik2411/Quiz-Genius#25]
Hi,

I suggest adding an image picker feature after signup to allow users to upload a profile image. This could enhance user experience by personalizing their homepage or profile.

Looking forward to your thoughts!

Best Regards,
Maryam Fatima

**Comment by yagnik2411** [comment]
- [ ] are you participating in hacktober-fest?
- [ ] are you participating in gssoc?
@MaRyamFatima1120

**Comment by yagnik2411** [comment]
@MaRyamFatima1120  go ahead and work on it

**Comment by MaRyamFatima1120** [comment]
Yes ,I am participating in GSSoC. Is it possible i also work from hacktober-fest?

**Comment by MaRyamFatima1120** [comment]
Hi, I’ve completed the image picker feature and would like to be considered for Hacktoberfest . I'm also participating in GSSOC & Hacktoberfest . Thank you!

**Comment by yagnik2411** [comment]
sorry for the inconvenience, i will your PR before EOD of 7-10-24

**Comment by MaRyamFatima1120** [comment]
Okay @yagnik2411  It's totally fine . we are no issue
