### ISSUE TITLE
add code_of_conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [yagnik2411/Quiz-Genius#27]
i want to work on this please add gssoc extd and hacktoberfest lable

**Comment by yagnik2411** [comment]
@kartikey369-ind Explain what a code of conduct.

**Comment by yagnik2411** [comment]
- [ ] are you participating in hacktober-fest?
- [ ] are you participating in gssoc?

**Comment by kartikey369-ind** [comment]
It provides guidelines for contributors while making contributions it allows to maintain healthy environment

**Comment by kartikey369-ind** [comment]
Yes iam participating in both hacktoberfest and Gssoc'24 extd

**Comment by Nimitshekhawat** [comment]
ohh , am new to  open source but not git hub .. 
seeing first time some got prase with question answers .. 
can we also try SIR??

**Comment by yagnik2411** [comment]
https://chat.whatsapp.com/FaQ28sTUMDPCY64JezzUoh
join this community for discussion

**Comment by yehiarasheed** [comment]
I agree, a code of conduct is essential for community-based repositories.
