### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by MaRyamFatima1120** [yagnik2411/Quiz-Genius#28]
Hi, I'm unable to add labels to this issue as a contributor. Could someone with the right permissions please add the appropriate labels? Thank you!

**Comment by yagnik2411** [comment]
that it our task not contributers

**Comment by MaRyamFatima1120** [comment]
I noticed that I’m unable to see the gear icon to add or manage labels, including the "gssoc" label. Other users have labels on their issues, but I don't seem to have access to this feature.

Could you please check my permissions and ensure that I have the ability to add labels to issues, as per our task? Thank you for your help?

**Comment by yagnik2411** [comment]
@yagnik2411 you are not a mentor and PA , so it is not your work

**Comment by MaRyamFatima1120** [comment]
Okay ,Thank you for clarification.
