### ISSUE TITLE
 Last Quiz Page Not Updating with Latest Attempted Questions and Solutions

### ISSUE THREAD

**Issue by lavitratyagi1** [yagnik2411/Quiz-Genius#29]
I encountered an issue in the quiz mobile app where the last quiz page (which shows the final quiz summary) is not updating correctly. It consistently displays the same set of questions and solutions, even after multiple new quiz attempts.

Expected Behavior:
The last quiz page should display the questions and solutions from the most recent quiz attempt.

Actual Behavior:
The last quiz page consistently shows the same set of questions and solutions, even after completing a new quiz. The questions and answers are not updated to reflect the latest quiz attempt.

Additional Info:
  - The issue persists even after restarting the app.
  - I have not seen any error messages or crash reports related to this behavior.

**Comment by lavitratyagi1** [comment]
Please assign it to me I want to work on it

**Comment by yagnik2411** [comment]
https://chat.whatsapp.com/FaQ28sTUMDPCY64JezzUoh
join this community for discussion
