### ISSUE TITLE
Missing Dialog before submitting a quiz

### ISSUE THREAD

**Issue by 17arindam** [yagnik2411/Quiz-Genius#38]
As there is no confirm submit modal user can submit a quiz unintentionally 
![image](https://github.com/user-attachments/assets/00fe77e5-14f7-4fe3-a2de-826ea820e17d)
so a modal should open which will ask to confirm before submiting a quiz

**Comment by 17arindam** [comment]
@yagnik2411 can you please assign me this issue

**Comment by Srilochan7** [comment]
i am a gssoc contributor can you please assign me this issue
