### ISSUE TITLE
Signup Issue – No Redirection to Username Page

### ISSUE THREAD

**Issue by MaRyamFatima1120** [yagnik2411/Quiz-Genius#41]
Hey Admin,

I wanted to let you know that I tried signing up multiple Gmail accounts, but the app doesn't navigate to the username page after completing the signup. It seems like the signup process completes successfully, but it doesn't redirect as expected.

Have you experienced this issue as well? Let’s see if we can figure it out together.

Thanks!

**Comment by MaRyamFatima1120** [comment]
I would like to inform you that my issue has been resolved. Thank you for your assistance!

**Comment by yagnik2411** [comment]
sorry for the inconvenience, i will check your PR before EOD of 7-10-24

**Comment by MaRyamFatima1120** [comment]
Please close this issue also. It's work now.
