### ISSUE TITLE
feat: UI enhancements to differentiate between Correct and Incorrect answers, more robust practices for questions with corresponding screenshots

### ISSUE THREAD

**Issue by yehiarasheed** [yagnik2411/Quiz-Genius#46]
## Description

Upon inspecting the project closely, I realized that the UI revolves around the same color scheme, and in the **_quizzes section_**, it would be helpful from a UI perspective to add a little flair like red buttons for incorrect answers and green(er) buttons for correct ones. Not to mention that even **basic robust coding practices** of adding special characters to questions (Strings) are not used and it shows in the screenshots. Therefore, to make the project more robust in terms of code and for it to be more appealing to the users, we should fix these issues.

## Screenshots
![image](https://github.com/user-attachments/assets/9635dbf9-3453-4103-af26-42395161311f)

As you can see above, even the quotation marks do not process correctly when being used for a question block and it looks super odd, not to mention that the incorrect and correct answers look the same. I would like to make the incorrect buttons red and correct buttons a bit darker green and make the UI look overall more appealing to the user. A user with a faint background in programming would not be interested if he was to see such screenshot. I would change the screenshot in the documentation too after making these changes. I will follow up on this issue with a PR fixing the issues and changing the corresponding screenshots in the docs.

I am a GSSoC '24 extd and hacktoberfest contributor, therefore please add the `gssoc-ext` and `hacktoberfest-accepted` labels to the PR.

**Comment by Abhi-0987** [comment]
Hello @yehiarasheed 

Great insights! I completely agree with your points. Using `MarkdownBody` for the question text would definitely resolve the issue with special characters not rendering properly. Differentiating correct and incorrect answers visually with distinct colors will also enhance the user experience. Excellent thoughts!

**Comment by yehiarasheed** [comment]
I'm glad we agree @Abhi-0987, great work on your issue too. Looking forward to our PRs.

**Comment by yagnik2411** [comment]
@yehiarasheed i will change SS by my self

**Comment by yehiarasheed** [comment]
This issue is also concerning changing the correct and incorrect buttons colours, and the faulty character render too (like the quotation) . Adding the screenshots was just one of the tasks I was going to solve in this issue.

**Comment by yagnik2411** [comment]
@yehiarasheed It is work not like this. you need to create new issues for every suggestion
