### ISSUE TITLE
User can select difficulty level of quiz

### ISSUE THREAD

**Issue by ezsarthak** [yagnik2411/Quiz-Genius#53]
By enabling this feature user can select between the difficulty levels. I added an MCQ type of quiz. So users can choose difficulty levels in both types of quizzes. 
Please assign this to me with Gssoc and Hackktoberfest label

**Comment by yagnik2411** [comment]
@ezsarthak  brother , don't do the task without assigning to you

**Comment by ezsarthak** [comment]
Sorry for it. Now u can assign the issue.

**Comment by yagnik2411** [comment]
@ezsarthak make PRs and mention issues number in that

**Comment by yagnik2411** [comment]
@ezsarthak  did you want to any type of help from @rishichirchi

**Comment by ezsarthak** [comment]
No, I have done this. Let my old PR get merged. I'll make a new PR for this issue
