### ISSUE TITLE
After restarting the app it asks for login again

### ISSUE THREAD

**Issue by ezsarthak** [yagnik2411/Quiz-Genius#54]
When we reopen the app it asks for login every time. Using Shared Prefs we can solve this problem. I'll also add the option to logout in Profile Section.
Please assign this to me with Gssoc and Hackktoberfest label

**Comment by Abhi-0987** [comment]
Hey @ezsarthak ,

 I see your issue overlaps with my current work #45 . Just wanted to mention that I'm already on it. Thanks for bringing it up!
