### ISSUE TITLE
(Enhancement) (level1) Add Github Greetings bot

### ISSUE THREAD

**Issue by KiranBaliga** [yagnik2411/Quiz-Genius#55]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by yagnik2411** [comment]
can you do auto labelling with bot?

**Comment by KiranBaliga** [comment]
@yagnik2411 I will add that feature to my level best.

**Comment by yagnik2411** [comment]
okay,but make PR first

**Comment by KiranBaliga** [comment]
@yagnik2411 If I may ask, what kind of labels are you looking to auto assign? let us say, gssoc-ext or hacktoberfest? the level labels will still need to be manually assigned due to the nature of the issues, if I am not wrong. Please shed a light on this.

**Comment by KiranBaliga** [comment]
@yagnik2411 Please review the PR and action accordingly. 

The details have been added to the PR.

Thank you!

**Comment by yagnik2411** [comment]
@KiranBaliga  if your user description of issues mentions gssoc-extend then gssoc-ext auto label, as well as level. The same goes for Hacktoberfest

**Comment by KiranBaliga** [comment]
@yagnik2411 The current PR meets the expectations of adding gssoc-ext and hacktoberfest.

**Comment by yagnik2411** [comment]
okay
