### ISSUE TITLE
Implement CI Pipeline for Automated Builds and Formatting Checks

### ISSUE THREAD

**Issue by Abhi-0987** [yagnik2411/Quiz-Genius#57]
During my attempt to build the APK, I encountered some issues that prevented the build from completing successfully. Additionally, I found several formatting inconsistencies and code analysis errors in the codebase.

So, to ensure the formats, styles and reduce the manual checks and tests, I propose the integration of a **CI pipeline** using GitHub Actions to automate the build process, check code formatting, and ensure overall code quality for every pull request and push to the `master` branch.

### Key Benefits:

- **Automated Code Formatting Check**: Detects any code formatting issues and ensures that the codebase adheres to consistent formatting rules. This check prevents unformatted code from being merged, helping maintain readability and style uniformity across the project.

- **Dependency Management**: Automatically fetches and installs all the required dependencies for the Flutter project. This ensures that the environment is fully set up with the latest packages and libraries before any further steps are executed.
  
- **Dart Code Analysis**: Performs static analysis on the Dart code, identifying potential code issues, bugs, or suboptimal code structures. This helps catch logical errors or warnings early in the development process, improving code quality and reliability.

- **APK Build Automation**: Builds the APK automatically with every push or pull request, addressing any issues in the build process early. This ensures that the app is always in a buildable state, helping to catch and resolve build-related problems efficiently.

Implementing this pipeline will:

- Streamline the development process by automating essential tasks like building, testing, and formatting checks.
- Reduce the time spent on manual builds and testing.
- Ensure that the codebase is always in a healthy, buildable state.
- Provide immediate feedback on code quality and any potential issues before they reach production.

Could you please assign this task to me? Looking forward to your feedback and suggestions! 😄

**Comment by yagnik2411** [comment]
@Abhi-0987  I don't know about the CI/CD pipeline if you are an expert in it and can do it without failure then I will assign It to you

**Comment by Abhi-0987** [comment]
@yagnik2411 I have worked on the this part in my previous projects too. We can currently integrate the repository with CI. Any PR's that has master as the base branch should pass the CI test to be able to merge after the integration. And even after merging the CI will be performed again to ensure that master branch is also error free.

**Comment by Abhi-0987** [comment]
I will work on this part first then go with other tasks, as this will keep the codebase error and bug free.

**Comment by yagnik2411** [comment]
@Abhi-0987 okay go for it
