### ISSUE TITLE
Add Issue Template to the Repository

### ISSUE THREAD

**Issue by JomanaMahmoud** [yagnik2411/Quiz-Genius#58]
I would like to contribute to this repository by adding an **issue template** to help standardize the issue reporting process. This would make it easier for users to report bugs, request features, and provide relevant information.

I am currently participating in **GSSoC-EXT** and **Hacktoberfest**, so I would appreciate it if you could add the labels `gssoc-ext` and `hacktoberfest-accepted` to this issue .

Could you assign this issue to me so I can start working on it?

**Comment by yagnik2411** [comment]
@JomanaMahmoud you can take a look at multiple issues, and make a standard format.
