### ISSUE TITLE
documentation of all code

### ISSUE THREAD

**Issue by yagnik2411** [yagnik2411/Quiz-Genius#59]
The project lacks comments and documentation of code.

Add documentation in the codebase using comments.

**Comment by areeba-farooq** [comment]
Hey, can you assign this to me?

**Comment by yagnik2411** [comment]
do you have any of your personal project, for demo?

**Comment by WednesdaySP** [comment]
@yagnik2411 I would like to work on this and improve the documentation of code, please assign me.

**Comment by KirolosMFahem** [comment]
anyone can fork and do the documentation and we'll review it
that applies to you @areeba-farooq @WednesdaySP 
and any other person wanna contribute

**Comment by WednesdaySP** [comment]
@KirolosMFahem okay I'll do it, please assign me
