### ISSUE TITLE
feat: UI enhancements to differentiate between Correct and Incorrect answers

### ISSUE THREAD

**Issue by yehiarasheed** [yagnik2411/Quiz-Genius#61]
## Description

Following up on #46 after @yagnik2411 said that he would change the screenshots himself, this leaves the issue where the color of incorrect question should still be changed to be able to differentiate between correct and incorrect answers visually, making it more appealing to the users. I will follow up on this issue with a PR, please assign the PR with `hacktoberfest-accepted` and `gssoc-ext` labels.

![image](https://github.com/user-attachments/assets/96d3b742-668a-4953-be53-7c3e2c3c36fc)

**Comment by yagnik2411** [comment]
add ss in issues of new design

**Comment by may-tas** [comment]
Can I work on this Issue if its still open ?

**Comment by yehiarasheed** [comment]
I'm finishing it up.
