### ISSUE TITLE
Add a "Quit" Button to Quiz Genius During an Active Quiz

### ISSUE THREAD

**Issue by anurag-026** [yagnik2411/Quiz-Genius#68]
Currently, once a quiz is started in the Quiz Genius app, there is no option to quit or exit the quiz midway. A user must complete the entire quiz to reach the "submit" button. This can be problematic if the user wishes to exit or abandon the quiz without completing all questions.

![Screenshot_20241009_003431](https://github.com/user-attachments/assets/cca26f96-ccde-43b2-8792-2e50be9d7c1b)

**Comment by yagnik2411** [comment]
@anurag-026 but that right way , i don't want to exit or abandon quizes
