### ISSUE TITLE
Quiz Result Screen Missing after Submission also remove "Correct/Incorrect" pop-up after answering questions

### ISSUE THREAD

**Issue by anurag-026** [yagnik2411/Quiz-Genius#69]
after selecting an answer (True/False), a pop-up message appears displaying "correct" or "incorrect." However, the pop-up message is disrupting the flow of the app and doesn't fit well visually.

![image](https://github.com/user-attachments/assets/e6b28b9e-23e8-410e-84cc-d8dff084ac14)

**Comment by anurag-026** [comment]
Once a user submits the quiz, the app is redirecting them straight to the home screen instead of displaying the quiz results. The expected behavior is that, after submission, the user should be taken to a dedicated result screen that summarizes their performance .

**Comment by yagnik2411** [comment]
#61  we have already this issues.
