### ISSUE TITLE
Improve Correct/Incorrect Answer Display for Quiz Results

### ISSUE THREAD

**Issue by anurag-026** [yagnik2411/Quiz-Genius#70]
The current UI for displaying correct and incorrect answers after a quiz submission can be improved. Instead of a simple Correct/Incorrect text  , the results should visually differentiate correct and incorrect answers by coloring the cards using green and red a bit like attached screenshot.
![image](https://github.com/user-attachments/assets/ca48ce4b-02fb-4304-850b-4cd0d54275b3)
previous
![image](https://github.com/user-attachments/assets/2a975585-ce83-4314-8c76-1f07392174df)

**Comment by yagnik2411** [comment]
@anurag-026  already #61  issues has the same idea
