### ISSUE TITLE
Alignment issues 

### ISSUE THREAD

**Issue by syeduzaif** [yagnik2411/Quiz-Genius#72]
Current Feature Description:
It has various alignment issues like on the login page, buttons are smaller, and in the text field, the example text is way too big. In the welcome page, text is not aligned in the center of the button, and the whole color theme is so bland that it cannot be differentiated between borders.

Proposed Improvement:
I will fix alignment issues, such as resizing the buttons on the login page for better usability. In the text field, I will reduce the font size of the example text for a more uniform appearance. Additionally, I will center-align the text in the welcome page button and redesign the entire color theme to be more vibrant and distinct.

**Reasons for Improvement:**
Improving the alignment and aesthetics of the app will enhance the overall user experience. A well-aligned interface promotes usability and accessibility, making it easier for users to navigate the application. A more vibrant color theme will also help in distinguishing different UI elements, making the app visually appealing and engaging.

**Acceptance Criteria:**

Buttons on the login page should be smaller and more touch-friendly.
The example text in the text fields should be reduced to a size that matches the overall design.
Text in the welcome page should be perfectly centered within the buttons.
The color theme should be updated to a more vibrant palette with distinct borders for different UI components.
Ensure consistency across all pages in terms of alignment and design elements.
Additional Context:
Consider user feedback and usability testing to guide the design changes. A/B testing can also be implemented after changes to evaluate user preference for the new design.

**Comment by yagnik2411** [comment]
@syeduzaif  right now, I am just allowing improvement. this is not valuable right now.
