### ISSUE TITLE
[BUG] overflow in drawer section

### ISSUE THREAD

**Issue by WednesdaySP** [yagnik2411/Quiz-Genius#76]
**Describe the bug**  
in drawer there is an overflow below user's name

**Screenshots**  
![WhatsApp Image 2024-10-10 at 18 13 52_d469ff63](https://github.com/user-attachments/assets/7d089fd5-101c-491a-8c2c-4ebe44643568)

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by WednesdaySP** [comment]
@KirolosMFahem could you please assign this to me, so I can start working on it

**Comment by KirolosMFahem** [comment]
you're on it
