### ISSUE TITLE
[BUG] error in code

### ISSUE THREAD

**Issue by WednesdaySP** [yagnik2411/Quiz-Genius#79]
**Describe the bug**  
after getting the updated code using git pull, some files showed error associated with WigetStateProperty, I guess this was a custom widget property but now it is not present in the code.

**Expected behavior**  
After performing the pull request the code should have been updated without any errors.

**Screenshots**  
![image](https://github.com/user-attachments/assets/e886059e-a307-4f8b-8bc2-0e079bbfeffe)

**Assignee**:
I would like to resolve these errors, please assign it to me.

**Comment by yagnik2411** [comment]
right materialstateproperty changed into widgetstate propertys

**Comment by WednesdaySP** [comment]
@yagnik2411 these errors still exists in the updated code

**Comment by yagnik2411** [comment]
i don't tackle any error
which version of flutter you use

**Comment by WednesdaySP** [comment]
@yagnik2411  I am using flutter version: 3.24.3, that code error issue is no more but now I am not able to login/ signup in the application.
