### ISSUE TITLE
[Documentation] Modification of README.md file & Creation of LICENSE File for project

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [yagnik2411/Quiz-Genius#81]
**Current Documentation**:
### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/8989cc16-2b35-45f0-8fc0-aced62fa1c9b)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors. I would like to update it and try to automate the process.

## 2. Addition of a LICENSE File to the project
The presence of a LICENSE file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a LICENSE file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.

**Proposed Changes**:

### 1) Add  animated line separators and add GSSoC 2024 Extended accepted banner
I would like to add line separators in the README.md file to separate sections and make the file more readable and attractive. I would also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.

![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/8ef5459b-aa74-459b-8960-819eb6e9544a)

The Team section will look more organized and readable and let the Contributors know whom to contact if they face any issues.

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/70ed2c59-55f1-4042-9aa9-7fe0a61309e4)

 I would like to update it and try to automate the process.
![image](https://github.com/user-attachments/assets/9c6bad7f-b4e5-4ed3-92e7-57872bf5712c)

## 2. Addition of a LICENSE File to the project
If a project does not have a **LICENSE** file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.
So, adding a **LICENSE** file is a best practice for open-source projects. I have added the LICENSE to your project and attached a reference image below to help you review the PR.
MIT LICENSE Reference:
![image](https://github.com/user-attachments/assets/c86b485a-b0c7-4717-8b0b-1a24191a3675)

**Reasons for Update**:
The following updates will make the projects more attractive and readable for the Contributors.

**Additional Context**:
N.A.

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to the documentation improvements.

**Comment by KirolosMFahem** [comment]
Hi @rajdeepchakraborty-rc

as for LICENSE: we're comfortable with MLP-2.0
and as for README: do as you please and we'll review it in the PR

so you're on it

**Comment by rajdeepchakraborty-rc** [comment]
> Hi @rajdeepchakraborty-rc
> 
> as for LICENSE: we're comfortable with MLP-2.0 as for README: do as you please and we'll review it in the PR
> 
> since it's not a direct contribution it will not be scored so you're on it

@KirolosMFahem Thanks for reaching out and assigning the PR to me. Though I did not understand the direct contribution part. Could you please explain that please? Why would the contribution not be scored?

**Comment by rajdeepchakraborty-rc** [comment]
Also please add the **hacktoberfest-accepted** tag to the issue

**Comment by KirolosMFahem** [comment]
As I said I can't add score to this issue so as well the hacktoberfest-accepted since it's being added with a level of contribution

**Comment by rajdeepchakraborty-rc** [comment]
> As I said I can't add score to this issue so as well the hacktoberfest-accepted since it's being added with a level of contribution

I was asking why you cannot add the level.

**Comment by KirolosMFahem** [comment]
it's either helping in improving the app or as for documentation explaining the app and the code

**Comment by rajdeepchakraborty-rc** [comment]
> it's either helping in improving the app or as for documentation explaining the app and the code

Ok.

**Comment by rajdeepchakraborty-rc** [comment]
Really sorry for the delay, I had a power cut at my place, which led to a delay in the assigned Issues.

**Comment by rajdeepchakraborty-rc** [comment]
Wanted to update you regarding the work:

This is how the Team section is looking for your project:

![image](https://github.com/user-attachments/assets/6a60be40-b0ca-4bd9-b199-d15cf23607b5)

**Comment by rajdeepchakraborty-rc** [comment]
Here is the new Contributor section:
![image](https://github.com/user-attachments/assets/907fc00b-3682-475e-9c15-3b61853641b0)

**Comment by rajdeepchakraborty-rc** [comment]
I am just doing some finishing touches and will open a PR soon.

**Comment by rajdeepchakraborty-rc** [comment]
@KirolosMFahem I assume you are the Project Mentor for this repository. So I was wondering shouldn't I add a profile for you too in the Team section? Any other Mentors too if there are any
Let me know your thoughts on this.

**Comment by KirolosMFahem** [comment]
there's also **Safiullahkorai-786** and **PrasadWilagama** are mentors

**Comment by rajdeepchakraborty-rc** [comment]
@yagnik2411 Can u please let me know if there are any other mentors for this repo, so that I can add them along with you

![image](https://github.com/user-attachments/assets/6a60be40-b0ca-4bd9-b199-d15cf23607b5)

**Comment by rajdeepchakraborty-rc** [comment]
I will go ahead and add the changes for now I guess.

**Comment by rajdeepchakraborty-rc** [comment]
@KirolosMFahem for now I have added just you as the project mentor along with the admin

**Comment by rajdeepchakraborty-rc** [comment]
I will open a PR soon
