### ISSUE TITLE
[Feature] to add light n dark mode toggle 

### ISSUE THREAD

**Issue by sv410** [yagnik2411/Quiz-Genius#89]
Feature Request: Light and Dark Mode Toggle
Description: A toggle button that allows users to switch between light and dark modes on the website. This feature enhances user experience by providing flexibility and reducing eye strain in different lighting environments.

Use Cases:

Reading at Night: Users can switch to dark mode to reduce eye strain when browsing the site at night.

Daytime Usage: Light mode ensures better visibility and readability in bright environments.

Personal Preference: Users can choose the mode that best suits their visual preference, enhancing comfort and satisfaction.

Additional Context:
![WhatsApp Image 2024-10-13 at 1 57 25 PM](https://github.com/user-attachments/assets/e525fef0-8820-4d02-820a-ac3e5e365525)

Discussions around user preference for dark mode in various forums.
![WhatsApp Image 2024-10-13 at 1 57 57 PM](https://github.com/user-attachments/assets/b7564bcb-3449-4e46-885a-b86a4956b4cb)

Screenshots showing how the interface looks in both light and dark modes.

Links to articles or studies highlighting the benefits of dark mode for reducing eye strain and improving battery life on OLED screens.

Assignee: Feel free to assign this issue to me, as I would like to contribute to its development.

**Comment by KirolosMFahem** [comment]
you're on it @sv410

**Comment by Navyachinta** [comment]
i would like to work on it @KirolosMFahem

**Comment by WednesdaySP** [comment]
@KirolosMFahem if he or she is not responding then I'm ready to work on this, please assign me.

**Comment by KirolosMFahem** [comment]
you can work on it either

- [ ]  the better the winner
- [ ]  or work together on it

@WednesdaySP @Navyachinta  @sv410 

I'm with work together opinion 

anyway you're all on it

**Comment by sv410** [comment]
@KirolosMFahem and @WednesdaySP shall we do it together? ill do the codes and can u guys make it single PR? is that possible

**Comment by sv410** [comment]
i will add the new file codes can u do the single PR to those three files 
i will name it as 
dark_light.html
dark_light.css
dark_light.js is that fine @WednesdaySP

**Comment by WednesdaySP** [comment]
@sv410 it is a flutter app you can't use html,css and js here.

**Comment by WednesdaySP** [comment]
@KirolosMFahem i have made a pr for this issue, please review it.
